before_script:
  - composer install --no-interaction --dev --prefer-dist
  - mkdir -p build/
  - mkdir -p build/logs
stages:
- test

#phpunit:
#  stage: test
#  script:
#    - php ./vendor/bin/phpunit


test:
  stage: test
  script:
    - find src/ -name '*.php' -print0 | xargs -0 -L 1 php -l
#    - find public/ -name '*.php' -print0 | xargs -0 -L 1 php -l
    - find tests/ -name '*.php' -print0 | xargs -0 -L 1 php -l
#    - php ./vendor/bin/testphase -i -d ./tests/testphase/ -b ./tests/testphase/bootstrap.php --verbose --server-host=localhost:8005